### ISSUE TITLE
Confused about `-thing` versions of replacement functions

### ISSUE THREAD

**Issue by hartzell** [emacsorphanage/anzu#98]
I'm confused about how the "thing" versions of the query replace functions work, I'd love it if you could give a more detailed explanation.  I'd be happy to update the README.md and PR if if/when I understand what's going on.

I've been trying to figure things out using a bit of Go code:

```go
type Inputs struct {
	Corrections []*Correction
	Features    []*Feature
	Oligos      []*Oligo
	Plasmids    []*Plasmid
}
```

The docs say this for `anzu-query-replace-at-cursor`

```
anzu-query-replace-at-cursor
Same as anzu-query-replace except from-string is symbol at cursor
```

If I call it with the cursor sitting on 'Feature', it prompts `Query replace regexp \_<Feature\_> with:`

The docs for `anzu-query-replace-at-cursor-thing` say this:

```
anzu-query-replace-at-cursor-thing
Same as anzu-query-replace-at-cursor except replaced region is specified by anzu-replace-at-cursor-thing.
```

If I call it the cursor sitting on 'Feature', it prompts `Query replace regexp \_<Feature\_> with:` (same as above).

The documentation for `anzu-replace-at-cursor-thing` say this:

```
anzu-replace-at-cursor-thing
Same as anzu-query-replace-at-cursor-thing except not query. This command is useful in refactoring such as changing variable name in the function.
```

which seems circular.  I get that it's the non-query version of `anzu-query-replace-at-cursor-thing` but can't figure out how the 'thing' version is different from the non-thing version.

The definition of `anzu-replace-at-cursor-thing`, 

```lisp
(defun anzu-replace-at-cursor-thing ()
  "anzu-query-replace-at-cursor-thing without query."
  (interactive)
  (let ((orig (point-marker)))
    (anzu--query-replace-common t
                                :at-cursor t
                                :thing anzu-replace-at-cursor-thing
                                :query nil)
    (goto-char (marker-position orig))
    (set-marker orig nil)))
```

uses `anzu-replace-at-cursor-thing`, which seems recursive and just leaves me confused....

I feel like I might be missing something simple/obvious, but....

Can you explain/demonstrate how the the `-thing` versions are different?

**THANKS!**

**Comment by syohex** [comment]
Sorry very late reply.

#### at-cursor
at-cursor uses input which is a symbol at cursor. And replace words with it  to jend of buffer.

![at-cursor](https://user-images.githubusercontent.com/554281/77822319-f0c67f00-7134-11ea-99e9-07bcc5757677.gif)

#### at-cursor-thing
while at-cursor-thing replaces only within `thing`(default is `defun`. You can change this value). Emacs has `thing` concept, `thing` is `word`, `symbol`, `line`, `defun` etc. We can get thing content, range or etc.

![at-cursor-thing](https://user-images.githubusercontent.com/554281/77822321-f1f7ac00-7134-11ea-8d23-ffbeb65f1cbd.gif)

Above example replace only within function. This is useful simple renaming refactoring. (NOTE: It looks only string match and is not smart. I recommend you to use smart refactoring tool rather than this)

My English is very poor, if you can write good English document, please write patch.

**Comment by gonewest818** [comment]
Thank you @syohex, makes perfect sense.

**Comment by hartzell** [comment]
Yes, *thank you*.  I'll take a look at wordsmithing the documentation a bit and PR it.

**Comment by hartzell** [comment]
Took a stab at improving this.  With the hint that @syohex provided I now understand what's going on.

The biggest stumbling block that I had is that `anzu-replace-at-cursor-thing` is the name of a function **and** a customization variable.
